---
kind: pipeline
type: exec
name: default

steps:
  - name: install
    image: composer
    commands:
      - composer install

  - name: test
    image: php:7
    commands:
      - vendor/bin/codecept run

trigger:
  branch:
    - master
  even:
    - push
